# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectRequestFive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectRequestFive
pod 'Alamofire'
pod 'SDWebImage', '5.12.6'
end
